name: Cargo doc workflow

on:
  workflow_call:
    inputs:
      PROJECT_ROOT:
        description: Path to th project to document
        type: string
        default: '.'
      ONLY_LIB:
        description: If document package's library
        type: boolean
        default: false
      RELEASE_MODE:
        description: If document optimized artifacts with the release profile
        type: boolean
        default: true
      OUTPUT_FOLDER:
        description: Path where to save output documentation
        type: string
        default: 'website_build'
      ADDITIONAL_OPTIONS:
        description: Additional options space-seperated list to pass to cargo doc command
        type: string
        default: ''
jobs:
  cargo_doc:
    runs-on: ubuntu-latest
    container:
      image: rust:1.57-buster
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # use to upload the repository content into the runner workspace: GITHUB_WORKSPACE
      - run: |
          cd ${{ inputs.PROJECT_ROOT }}
          echo "CIWORKSPACE_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PROJECT_ROOT_RELATIVE_PATH=$(pwd)" >> $GITHUB_ENV # Create a new  environment variable PROJECT_ROOT_RELATIVE_PATH
      - run: |
          cd ${{ inputs.PROJECT_ROOT }} # IMPORTANT to move in the PROJECT_ROOT directory before execution any command
          if [ ! -f "Cargo.toml" ]; then
            echo "ERROR --> Any Cargo.toml file isn't present in the given root project  folder ${{ inputs.PROJECT_ROOT }}"
          fi
      - run: | # Create copies of inputs variables that need to be updated
          echo "ADDITIONAL_OPTIONS=${{inputs.ADDITIONAL_OPTIONS}}" >> $GITHUB_ENV
          echo "OUTPUT_FOLDER=${{inputs.OUTPUT_FOLDER}}" >> $GITHUB_ENV
      - run: |
          if [ ${{ inputs.ONLY_LIB }} ]; then
            echo "ADDITIONAL_OPTIONS=${{env.ADDITIONAL_OPTIONS}} --lib" >> $GITHUB_ENV  # variable update statement
          fi
      - run: |
          if [ ${{ inputs.RELEASE_MODE }} ]; then
            echo "ADDITIONAL_OPTIONS=${{env.ADDITIONAL_OPTIONS}} --release" >>  $GITHUB_ENV
          fi
      - run: |
          if [ ! ${{env.PROJECT_ROOT_RELATIVE_PATH}} -ef ${{env.CIWORKSPACE_PATH}} ];  then
            echo "OUTPUT_FOLDER=$GITHUB_WORKSPACE/${{ inputs.OUTPUT_FOLDER }}" >>  $GITHUB_ENV
          fi   
      - run: |
          cd ${{ inputs.PROJECT_ROOT }} # IMPORTANT to move in the PROJECT_ROOT directory before execution any command
          cargo doc --target-dir ${{env.OUTPUT_FOLDER}} ${{ env.ADDITIONAL_OPTIONS }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cargo_doc build
          path: ${{ env.OUTPUT_FOLDER }}